#!/bin/bash

case $1 in
    "standard")
        export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;94m\]\u@\h\[\033[00m\]:\[\033[1;32m\]\w\[\033[00m\]\$ "
        ;;
    "small")
        export PS1="\[\033[1;32m\]\W\[$(tput sgr0)\]\[\033[0;0;0m\]$ "
        ;;
    "small2")
        export PS1="\e[32;1m\w\[$(tput sgr0)\]\e[0;0;0m$ "
        ;;
    "ultrasmall")
        export PS1="$ "
        ;;
    "enter")
        export PS1='\[\e[0;1m\]⎡ \[\e[0;1;94m\]\u\[\e[0;1;94m\]@\[\e[0;1;94m\]\H\[\e[0m\]:\[\e[0;1;92m\]\w\n\[\e[0;1m\]⎣ \[\e[0m\]$\[\e[0m\] '
        ;;
    "entersmall")
        export PS1='\[\e[0;1m\]⎡ \[\e[0;1;94m\]\w \[\e[0;1m\](\[\e[0;1;92m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\[\e[0;1m\])\n\[\e[0;1m\]⎣ \[\e[0m\]$ \[\e[0m\]'
        ;;
    "entersmall2")
        export PS1='\[\e[0;1m\]⎡ \[\e[0;1;94m\]\W \[\e[0;1m\](\[\e[0;1;92m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\[\e[0;1m\])\n\[\e[0;1m\]⎣ \[\e[0m\]$ \[\e[0m\]' 
        ;;
    *)
        echo "Unknown prompt type '$1'"
        ;;
esac

export TESTTEST="test hallo"
